local tags = require("ideaDrop.features.tags")

describe("extract_tags", function()
	it("extracts simple tags", function()
		local result = tags.extract_tags("This has #work and #personal tags")
		assert.equals(2, #result)
		assert.equals("personal", result[1]) -- sorted
		assert.equals("work", result[2])
	end)

	it("handles hyphenated tags", function()
		local result = tags.extract_tags("#my-project is cool")
		assert.equals(1, #result)
		assert.equals("my-project", result[1])
	end)

	it("handles underscore tags", function()
		local result = tags.extract_tags("#my_tag here")
		assert.equals(1, #result)
		assert.equals("my_tag", result[1])
	end)

	it("deduplicates tags", function()
		local result = tags.extract_tags("#work and #work again")
		assert.equals(1, #result)
		assert.equals("work", result[1])
	end)

	it("filters common words", function()
		local result = tags.extract_tags("#the #and #or #but #work")
		assert.equals(1, #result)
		assert.equals("work", result[1])
	end)

	it("returns empty for no tags", function()
		local result = tags.extract_tags("No tags here at all")
		assert.equals(0, #result)
	end)

	it("handles multiple lines", function()
		local result = tags.extract_tags("Line one #alpha\nLine two #beta\nLine three #gamma")
		assert.equals(3, #result)
		assert.equals("alpha", result[1])
		assert.equals("beta", result[2])
		assert.equals("gamma", result[3])
	end)

	it("returns sorted tags", function()
		local result = tags.extract_tags("#zebra #apple #mango")
		assert.equals("apple", result[1])
		assert.equals("mango", result[2])
		assert.equals("zebra", result[3])
	end)
end)

describe("is_common_word", function()
	it("identifies common words", function()
		assert.is_true(tags.is_common_word("the"))
		assert.is_true(tags.is_common_word("and"))
		assert.is_true(tags.is_common_word("or"))
	end)

	it("does not flag normal words", function()
		assert.is_false(tags.is_common_word("work"))
		assert.is_false(tags.is_common_word("project"))
		assert.is_false(tags.is_common_word("todo"))
	end)
end)
